language: node_js

node_js:
  - "6"
  - "8"
  - "node"

services:
  - redis

cache:
  npm: true
  directories:
    - ~/.cache
    - ~/.nvm
    - ~/.npm

install:
  - npm install

script:
  - npm test

notifications:
  email: false
